site_name: Origins Documentation
nav:
    - Home: index.md
    - Types:
        - Power Types: power_types.md
        - Data Types: data_types.md
    - Conditions:
        - Biome Conditions: biome_conditions.md
        - Block Conditions: block_conditions.md
        - Damage Conditions: damage_conditions.md
        - Entity Conditions: entity_conditions.md
        - Fluid Conditions: fluid_conditions.md
        - Item Conditions: item_conditions.md
    - Actions:
        - Block Actions: block_actions.md
        - Entity Actions: entity_actions.md
        - Item Actions: item_actions.md
    - Miscellaneous:
        - Origins: origins.md
        - Keybindings: misc/keybindings.md
        - Resource Bars: misc/resource_bars.md
        - Vanilla Damage Sources: misc/vanilla_damage_sources.md
theme: readthedocs
separator: '_'
